[package]
name = "outbox-publisher"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
tokio.workspace = true
ydb.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
rdkafka = { workspace = true, optional = true }
prometheus.workspace = true
axum.workspace = true
lazy_static.workspace = true

[features]
default = ["kafka"]
kafka = ["rdkafka"]